version: '3.8'

services:
  custom_server:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: custom_server
    networks:
      - internal_network
    expose:
      - "81" 

  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - custom_server
    ports:
     - "80:8080"
    networks:
     - internal_network
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  internal_network:
    driver: bridge